import {
  faGithub,
  faMedium,
  faYoutube,
  faTwitter,
  faBitcoin,
  faEthereum,
  faFacebook,
  faReddit,
  faTelegram,
  faBitbucket,
  faDiscord,
  faLinkedin,
  faTiktok,
  faInstagram,
  faAppStoreIos,
  faGooglePlay,
} from "@fortawesome/free-brands-svg-icons";

import {
  faStar as faStarFilled,
  faBookmark as faBookmarkFilled,
  faHeart as faHeartFilled,
  faLightbulb as faLightbulbFilled,
} from "@fortawesome/free-solid-svg-icons";
import {
  faStar as faStarEmpty,
  faBookmark as faBookmarkEmpty,
  faHeart as faHeartEmpty,
  faLightbulb as faLightbulbEmpty,
} from "@fortawesome/free-regular-svg-icons";

import {
  faAngleUp,
  faAngleDown,
  faAngleRight,
  faAngleLeft,
  faCaretUp,
  faCaretDown,
  faCaretRight,
  faCaretLeft,
  faSun,
  faMoon,
  faBars,
  faEllipsis,
  faHouse,
  faSearch,
  faUser,
  faCog,
  faBell,
  faPlus,
  faXmark,
  faCheck,
  faSliders,
  faMagnifyingGlass,
  faEye,
  faLayerGroup,
  faFire,

} from "@fortawesome/free-solid-svg-icons";

export const icons = {
  faGithub,
  faMedium,
  faYoutube,
  faTwitter,
  faBitcoin,
  faEthereum,
  faFacebook,
  faReddit,
  faTelegram,
  faBitbucket,
  faDiscord,
  faLinkedin,
  faTiktok,
  faInstagram,
  faAppStoreIos,
  faGooglePlay,

  faStarFilled,
  faBookmarkFilled,
  faHeartFilled,
  faLightbulbFilled,
  faStarEmpty,
  faBookmarkEmpty,
  faHeartEmpty,
  faLightbulbEmpty,
  faAngleUp,
  faAngleDown,
  faAngleRight,
  faAngleLeft,
  faCaretUp,
  faCaretDown,
  faCaretRight,
  faCaretLeft,
  faSun,
  faMoon,
  faBars,
  faEllipsis,
  faHouse,
  faSearch,
  faUser,
  faCog,
  faBell,
  faPlus,
  faXmark,
  faCheck,
  faSliders,
  faMagnifyingGlass,
  faEye,
  faLayerGroup,
  faFire,
};
