import {
  faAppStoreIos,
  faBitbucket,
  faBitcoin,
  faDiscord,
  faEthereum,
  faFacebook,
  faGithub,
  faGooglePlay,
  faInstagram,
  faLinkedin,
  faMedium,
  faReddit,
  faTelegram,
  faTiktok,
  faTwitter,
  faYoutube,
} from "@fortawesome/free-brands-svg-icons";

import {
  faBookmark as faBookmarkEmpty,
  faHeart as faHeartEmpty,
  faLightbulb as faLightbulbEmpty,
  faStar as faStarEmpty,
} from "@fortawesome/free-regular-svg-icons";
import {
  faBookmark as faBookmarkFilled,
  faHeart as faHeartFilled,
  faLightbulb as faLightbulbFilled,
  faStar as faStarFilled,
} from "@fortawesome/free-solid-svg-icons";

import {
  faAngleDown,
  faAngleLeft,
  faAngleRight,
  faAngleUp,
  faBars,
  faBell,
  faCaretDown,
  faCaretLeft,
  faCaretRight,
  faCaretUp,
  faCheck,
  faCircleNotch,
  faCog,
  faEllipsis,
  faEye,
  faFileSignature,
  faFire,
  faHouse,
  faLayerGroup,
  faMagnifyingGlass,
  faMoon,
  faPlus,
  faSearch,
  faSliders,
  faSpinner,
  faSun,
  faUser,
  faUserSlash,
  faXmark,
} from "@fortawesome/free-solid-svg-icons";

export {
  faGithub,
  faMedium,
  faYoutube,
  faTwitter,
  faBitcoin,
  faEthereum,
  faFacebook,
  faReddit,
  faTelegram,
  faBitbucket,
  faDiscord,
  faLinkedin,
  faTiktok,
  faInstagram,
  faAppStoreIos,
  faGooglePlay,
  faStarFilled,
  faBookmarkFilled,
  faHeartFilled,
  faLightbulbFilled,
  faStarEmpty,
  faBookmarkEmpty,
  faHeartEmpty,
  faLightbulbEmpty,
  faAngleUp,
  faAngleDown,
  faAngleRight,
  faAngleLeft,
  faCaretUp,
  faCaretDown,
  faCaretRight,
  faCaretLeft,
  faSun,
  faMoon,
  faBars,
  faEllipsis,
  faHouse,
  faSearch,
  faUser,
  faCog,
  faBell,
  faPlus,
  faXmark,
  faCheck,
  faSliders,
  faMagnifyingGlass,
  faEye,
  faLayerGroup,
  faFire,
  faCircleNotch,
  faSpinner,
  faUserSlash,
  faFileSignature,
};
